name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome! 👋 Thank you for opening your first issue. If you have any questions or need assistance, feel free to ask. Happy coding!"
        pr-message: "Hello there! 🚀 Thanks for your pull request. We appreciate your contribution! If you have any questions or if there's anything we can do to help, don't hesitate to let us know. Looking forward to collaborating with you!"

